<a href="https://colab.research.google.com/github/Yezz1n/ESAA_OCT/blob/main/ESAA_fourth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#사이킷런

:파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리

가장 쉽고 효율적인 개발 라이브러리 제공

* 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향-> 가장 파이썬 스러운 API 제공

* 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편안한 프레임워크와 API 제공

* 오랜 기간 실전 환경에서 검증됐으며, 매우 많은 환경에서 사용되는 성숙한 라이브러리

In [ ]:
#사이킷런 설치
#pip install scikit-learn

SyntaxError: ignored

##붓꽃 품종 예측하기

:붓꽃 데이터 세트는 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피처 기반으로 꽃의 품조 예측


###분류
: 대표적인 지도학습 방법의 하나

###지도학습
:학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측한다.

-> 지도학습은 명확한 정답이 주어진 데이터를 먼저 학습한 뒤 미지의 정답을 예측 하는 방식

* 학습을 위해 주어진 데이터 세트: 학습 데이터 세트
* 머신러닝 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트: 테스트 데이터 세트




* sklearn
  * sklearn.datasets: 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임

  * sklearn.tree: 트리 기반 ML알고리즘을 구현한 클래스의 모임
  
  * sklearn.model_selection: 학습 데이터와 검증 데이터, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임
      * 하이퍼 파라미터: 머신러닝 알고리즘 별로 최적의 학습을 위해 직접 입력하는 파라미터들의 통칭/이를 통해 머신러닝 알고리즘의 성능을 튜닝할 수 있다.

In [ ]:
import sklearn
import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [ ]:
iris=load_iris()

#iris.data는  iris 데아터 세트에서 피처만으로 된 데이터를 numpy로 가지고 있다

iris_data=iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값)데이터를 numpy로 가지고 있다.

iris_label=iris.target

print('iris target 값:',iris_label)
print('iris target 명:',iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 전환

iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

레이블(label)은 0,1,2 3가지 값으로 돼 있으며 0이 setosa 품종, 1이 versicolor 품종, 2가 virginica 품종을 의미

학습용 데이터와 테스트용 데이터를 분리

<font color='red'> 반드시 분리 필요

:뛰어난 성능 평가 위해서는 테스트 데이터 세트가 필요

->사이킷런은 train_test_split() API 제공

*  train_test_split() 을 이용하면 학습 데이터와 테스트 데이터를 test_size 파라미터 입력 값을 비율로 쉽게 분할

ex) test_size=0.2로 입력 파리미터 설정 시 전체 데이터 중 테스트 데이터가 20% 학습 데이터가 80%로 데이터를 분할

  * train_test_split() 호출 시 무작위로 데이터를 분리하므로 random_state를 지정해야 일정한 숫자값으로 분리 가능==seed같은 기능


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

#iris_data:피쳐 데이터 세트/iris_label:레이블 데이터 세트/test_size:전체 데이터 세트 중 테스트 데이터 세트의 비율
#random_state:호출 시 마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값

* 사이킷런의 의사결정 트리 클래스:DecisionTreeClassifier
   * fit() 메소드에 학습용 피처 뎅터 속성과 결정값 데이터 세트를 입력해 호출하면 학습 수행


In [ ]:
dt_clf=DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

   * DecisionTreeClassifier를 이용해 예측 수행 가능
* 예측 시 반드시 학습 데이터가 아닌 다른 데이터를 이용해야함, 일반적으로 testdata 이용
 * predict()

In [ ]:
pred=dt_clf.predict(X_test)

* 정확도 측정
:예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는 지표
 * accuacy_count()

In [ ]:
#붓꽃 데이터의 붓꽃 품종과 실제 테스트 데이터 세트의 붓꽃 품종이 얼마나 일치하는지 확인
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


<font color='blue'> 예측 프로세스 정리

1. 데이터 세트 분리; 데이터를 학습 데이터와 테스트 데이터로 분리

2. 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습

3. 예측 수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류를 예측(여기선 붓꽃 종류)

4. 평가: 이렇게 예측된 결과값과 테스트 데이터의 실제 결과값을 비교해 ML 모델 성능을 평가


###사이킷런의 기반 프레임워크 익히기

###Estimator 이해 및 fit(),predict() 메서드

* fit(): ML 모델 학습 위해서

* predict(): 학습된 모델 예측

->지도학습의 주요 두 축인 분류와 회귀의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 두가지만을 이요해서 간단하게 학습과 예측 결과 반환

* Classifier :분류 알고리즘을 구현한 클래스

* Regressor:회귀 알고리즘을 구현한 클래스

  ->둘을 합쳐 "Estimator" 클래스라고 부른다
(fit() predict() 내부에서 구현하고 있다)

  *  cross_val_score() 같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스의 경우 이 Estimator을 인자로 받음

 * 인자로 받은 Estimator에 대해서 cross_val_score(),GridSearchCV.fit() 함수 내에서 이 Estimator의 fit() 과 predict()를 호출해서 평가를 하거나 하이퍼 파라미터 튜닝을 수행

 * 비지도학습인 차원 축소, 클러스터링, 피처 추출 등을 구현한 클래스 역시 대부분 fit()과 transform()을 적용
  * fit(): 지도학습과 의미 다름. 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞춤
  * transform(): 사전 구조 맞춘 이후 입력 데이터의 차원 변호나, 클러스터링, 피처 추출 등의 실제 작업은 transform()으로 수행
  * fit_transform(): 둘을 하나로 결합, 별도로 호출할 필요를 줄여주지만, 사용에 약간 주의 필요

###사이킷런의 주요 모듈

* 예제 데이터
 * sklearn.datasets: 사이킷런에 내장되어 있는 예제로 제공하는 데이터 세트
* 피처 처리
 * sklearn.preprocessing: 데이터 전처리에 필요한 다양한 가공 기능 제공(문자열을 숫자형 코드 값으로 인코딩, 정규화, 스케일링)
 * sklearn.feature_selection: 알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능을 제공
 * skelearn.feature_extraction
  * 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는데 사용됨

    ex) 예를 들어 텍스트 데이터에서 Count Vectorizer나 Tf-ldf Vectorizer 등을 생성하는 기능 제공
  * 텍스트 데이터의 피처 추출은 sklearn.feature_extraction, text 모듈에 이미지 데이터의 피처 추출은 sklearn.feature_extraction.image 모듈에 지원 API가 있음

* 피처 처리&차원 축소
 * sklearn.decomposition:차원 축소와 관련한 알고리즘을 지원하는 모듈. PCA,NMF, Truncated SVD등을 통해 차원 축소 기능을 수행할 수 있음

* 데이터 분리, 검증& 파라미터 튜닝
 * sklearn.model_selection: 교차 검증을 위한 학습용/ 테스트용 분리, 그리드 서치로 최적 파라미터 추출 등의 API 제공

* 평가 
 * sklearn.metrics: 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공
  * accuracy, precision, recall, ROC_AUC, RMSE 등 제공

* 알고리즘
 * sklearn.ensemble :앙상블 알고리즘 제공 
    * 랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 등 제공
 * sklearn,linear_model: 주로 선형 회귀, 릿지, 라쏘 및 로지스틱 회귀 등 회귀 관련 알고리즘을 지원, 또한, SGD 관련 알고리즘도 제공
 * sklearn.naive_bayes: 나이브 베이즈 알고리즘 제공, 가우시안 NB, 다항 분포 NB
 * sklearn.neighbors :최근접 이웃 알고리즘 제공, K-NN
 * sklearn.svm: 서포트 벡터 머신 알고리즘 제공
 * sklearn.cluster : 비지도 클러스터링 알고리즘 제공(K-평균, 계층형, 
 DBSCAN)
* 유틸리티
 * sklearn.pipeline: 피처 처리 등의 변환과 ML 알고리즘 학습, 예측 등을 함께 묶어 실행할 수 있는 유틸리티 제공



일반적으로 머신러닝 모델을 구축하는 주요 프로세스: 피처의 가공, 변경, 추출을 수행하는 피처 처리, ML 알고리즘 학습/예측 수행, 모델 평가의 단계 반복적으로 수행

####내정된 예제 데이터 세트
: 사이킷런 내부에 데이터 세트 
 
* datasets.load_boston():회귀 용도, 미국 보스톤의 집 피처들과 가격에 대한 데이터 세트

* datasets.load_breast_cancer(): 분류 용도, 위스콘신 유방암 피처들과 악성/음성 레이블 데이터 세트

* datasets.load_diabetes(): 회귀 용도, 당뇨 데이터 세트

* datasets.load_digits(): 분류 용도 0-9까지 숫자의 이미지 픽셀 데이터 세트

* datasets.load_iris(): 분류 용도 붓꽃에 대한 피처를 가진 데이터 세트


* fetch 계열의 명령은 인터넷에서 내려받아서 사용 데이터

  * fetch_covtype(): 회귀 분석용 토지 조사 자료
  * fetch_20newsgroups(): 뉴스 그룹 텍스트 자료
  * fetch_olivetti_faces(): 얼굴 이미지 자료
  * fetch_lfw_people():  얼굴 이미지 자료
  * fetch_lfw_party(): 얼굴 이미지 자료
  * fetch_rcv1(): 로이터 뉴스 말뭉치
  * fetch_mldata():ML 웹사이트에서 다운로드

* 분류와 클러스터링을 위한 표본 데이터 생성기 
 * datasets.make_classifications(): 분류를 위한 데이터 세트를 만듦. 특히, 높은 상관도, 불필요한 속성 등의 노이즈 효과를 위한 데이터를 무작위로 생성해줌
 * datasets.make_blobs():클러스터링을 위한 데이터 세트를 무작위로 생성해줌. 군집 지정 개수에 따라 여러가지 클러스터링을 위한 데이터 세트를 쉽게 만들어줌

 사이킷런 내장된 이 데이터 세트는 일반적으로 딕셔너리 형태로 돼있음


 키는 보통 data, target, target_name, feature_names,DESCR로 구성돼 있음

 * data: 피처의 데이터 세트
 * target: 분류 시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트
 * target_names: 개별 레이블의 이름
 * feature_names:피처의 이름
 * DESCR:데이터 세트에 대한 설명과 각 피처의 설명
  * data,target은 넘파이 배열 타입
  * target_names,feature_names는 넘파이 배열 또는 파이썬 리스트
  * DESCR 스트링 타입
  --> 피처의 데이터 값을 반환받기 위해서는 내장 데이터 세트 API를 호출한 뒤에 그 key 값을 지정하면 된다

  


In [ ]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


: 이 때 Bunch 클래스는 파이썬 딕셔너리 자료형과 유사
데이터 세트에 내장돼 있는 대부분의 데이터 세트는 이와 같이 딕셔너리 형태의 값을 반환


In [ ]:
#딕셔너리 형태의 데이터 세트의 key 값 확인하기

keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


:데이터 키는 피처들의 데이터 값을 가리킴

데이터 세트가 딕셔너리 형태이기 때문에 피처 데이터 값을 추출하기 위해서는 데이터 세트.data를 이용하면 됨

target,feature_names,DESCR key가 가리키는 데이터 값의 추출도 동일하게 수행하면 됨



In [ ]:
#load_iris()가 반환하는 객체의 키인 feature_names,target_name,data,target이 가리키는 값?
print('\n feature_names의 type:',type(iris_data.feature_names))
print(' feature_names의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)


print('\n target_names의 type:',type(iris_data.target_names))
print('target_names의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:',type(iris_data.target))
print('target의 shape:',iris_data.target)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
target의 shape: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


###Model Selection 모듈

사이킷런의 model_selection 모듈은 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, 그리고 estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공

#### train_test_split(): 학습 데이터/ 테스트 데이터 세트 분리
학습 데이터 세트 기반으로 예측하였기 때문에 정확도 위해 원본 데이터에서 학습 및 테스트 데이터 세트를 분리 필요 O
* train_test_split():첫번째 파라미터로 피처 데이터 세트, 두번째 파라미터로 레이블 데이터 세트, 선택적으로 다음 파라미터 입력받기도 함
 * test_size: 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인가를 결정. 디폴트는 0.25
 * train_size: 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것인가를 결정. test_size parameter를 통상적으로 사용하기 때문에 train_size는 잘 사용하지 x
 * shuffle: 데이트를 분리하기 전에 데이터를 미리 섞을지를 결정. 디폴트는 True, 데이터를 분산시켜서 좀 더 효율적인 학습 및 테스트 데이터 세트를 만드는 데 사용
 * random_state: 호출할 때마다 동일한 학습/ 테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값. train_test_split()은 호출 시 무작위로 데이터를 분리하므로 random_state를 지정하지 않으면 수행할 때마다 다른 학습.테스트 용 데이터를 생성

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target

dt_clf.fit(train_data,train_label)

#학습 데이터 세트로 예측 수행
pred=dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label,pred))

예측 정확도: 1.0


In [ ]:
#붓꽃 데이터 세트를 train_test_split()을 이용해 테스트 데이터 세트를 전체의 30%, 학습 데이터 세트를 70%로 분리. 
dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)

#학습 데이터 기반 DecisionTreeClassifier을 학습하고 이 모델을 이용해 예측 정확도를 측정
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


학습을 위한 데이터의 양을 일정 수준 이상으로 보장하는 것도 중요하지만, 학습된 모델에 대해 다양한 데이터를 기반으로 예측 성능을 평가해보는 것도 중요

###교차 검증
* 과적합: 모델이 학습 데이터에만 과도하게 최적화 되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어짐.

학습용 데이터와 테스트 데이터를 이용해 평가하다 보면 테스트 데이터에만 최적의 성능을 발휘할 수 있도록 편향되게 모델 유도하는 경향이 생겨 다르 테스트 데이터가 들어오면 성능이 저하될 수 있다.

* 교차 검증: 많은 학습과 검증 세트에서 알고리즘 학습과 평가를 수행한 후에 테스트 데이터 세트에 대해 평가

ML은 데이터에 기반. 데이터는 이상치, 분포도, 다양한 속성값, 피처 중요도 등 여러가지 ML에 미치는 요소를 가지고 있다.

데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행. 각 세트에서 수행한 평가 결과에 따라 하이퍼 파라미터 튜닝 드으이 모델 최적화를 더 손쉽게 할 수 있다.

대부분의 ML 모델의 성능 평가는 교차 검증 기반을 1차 평가를 한 뒤에 최종적으로 테스트 epdlxj tpxm 적용해 평가하는 프로세스.

ML 모델의 성능 평가 대부분은 교차 검증 기반으로 1차 평가를 한 뒤에 최종적으로 테스트 데이터 세트에 적용해 평가하는 프로세스
ML에 사용되는 데이터 세트를 세분화해서 학습, 검증, 테스트 데이터 세트로 나눌 수 있다.

테스트 데이터 세트 외에 별도의 검증 데이터 세트를 둬서 최종 평가 이전에 학습된 모델을 다양하게 평가하는데 사용

#### K 폴드 교차 검증
:가장 보편적. K개의 데이터 폴드 세트를 만들어서 K번칸큼 각 폴트 세트에 학습과 검증 평가 방법을 반복적으로 수행하는 방법

ex) K=5
5개의 폴드된 데이터 세트를 학습과 검증을 위한 데이터 세트로 변경하면서 5번 평가를 수행한 뒤, 이 5개의 평가를 평균한 결과를 가지고 예측 성능을 평가
-데이터 세트를 5등분
-첫번째 반복에서 처음부터 4개 등분을 학습 데이터 세트, 마지막 5번째 등분 하나를 검증 데이터 세트로 설정하고 학습 데이터 세트에서 학습 수행, 검증 데이터 세트에서 평가를 수행
-첫번째 평가를 수행하고 나면 이제 두번째 반복에서 다시 비슷한 학습과 평가 작업을 수행
->이번에는 학습 데이터와 검증 데이터를 변경(처음부터 3개 등분까지, 그리고 마지막 5번째 등분을 학습 데이터 세트로 4번째 등분 하나를 검증 데이터 세트로 설정
-반복


:KFold StratifiedKFold 클래스


In [ ]:
#KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 Kfold 객체와 폴드 세트별 정학도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [ ]:
n_iter=0
#KFold 객체의 split()을 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index,test_index in kfold.split(features):
  #kfold.split.()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train,X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1
  #반복 시마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:',np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


#### Stratified K 폴드
:불균형한 분포도를 가진 레이블 데이터 집합을 위한 K폴드 방식<왜곡된 데이터>

->불균형한 원본 데이터의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트를 분배 
ex)대출 사기

* 일반적으로 분류에서 교차검증은 Stratified K 폴드로 분할돼야 함
 *회귀에서는 지원되지 않음:회귀의 결정값은 이산값 형태의 레이블이 아니라 연속된 숫자값이기 때문에 결정값 별로 분포를 정하는 의미가 없다

In [ ]:
#setosa, versicolor, virginica 품종 모두가 50개
#이슈가 발생하는 현상을 도출하기 위해 3개의 폴드 세트를 Kfold로 생성하고, 각 교차 검증 시마다 생성되는 학습/ 검증 레이블 데이터 값의 데이터 값 분포도 확인

kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('## 교차검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n',label_train.value_counts())
  print('검증 레이블 데이터 분포:\n',label_test.value_counts())
  iris_df['label'].value_counts()

## 교차검증:1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차검증:2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차검증:3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


:Kfold로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결해줌


In [ ]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index,test_index in skf.split(iris_df,iris_df['label']):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('## 교차 검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n',label_train.value_counts())
  print('검증 레이블 데이터 분포:\n',label_test.value_counts())

## 교차 검증:1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [ ]:
#붓꽃

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index,test_index in skfold.split(features,label):
  #split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]


  #학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)

  #반복 시마다 정확도 측정
  n_iter+=1
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증도 정확도:',np.round(cv_accuracy,4))
print('## 평균 검증 정확도:',np.mean(cv_accuracy))


1 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

2 교차 검증 정확도:0.94, 학습 데이터 크기:100, 검증 데이터 크기:50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

3 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증도 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


###cross_val_score():교차검증 더 간편하게 할 수 있는 사이킷런의 API

KFold로 데이터 학습하고 예측하는 코드
1. 폴드 세트 설정
2. for루프에서 반복으로 학습 및 테스트 데이터의 인덱스를 추출
3. 반복적으로 학습과 예측 수행하고 예측 성능을 반환

=>cross_val_score()은 한번에 수행


```
cross_val_score(estimator,X,y=None,scoring=None,n_jobs=1,verbose=1,fit_params=None,pre_dispatch='2*n_jobs')
```

* estimator:사이킷런의 분류 알고리즘 클래스인 Classifier 또는 회귀 알고리즘 클래스인 Regressor
* X:피처 데이터 세트
* y:레이블 데이터 세트
* scoring: 예측 성능 평가 지표
* cv: 교차 검증 폴드 수
  * 수행 후 반환 값 scoring 파라미터로 지정된 성능 지표 측정값을 배열형태로 반환
  * classifier 입력되면 Stratified K 폴드 방식으로 레이블값의 분포에 따라 학습/테스트 세트를 분할(회귀 시는 K 폴드 방식)

:cv로 지정된 횟수만큼 scoring 파라미터로 지정된 평가 지표로 평가 결과값을 배열로 반환
일반적으로 이를 평균해 평균 수치로 사용

* API 내부에서 fit(학습) predict(예측) 평가(evaluation)시켜주어 간단하게 교차 검증 수행할 수 있다

붓꽃 데이터의 cross_val_score() 수행결과와 앞 예제의 붓꽃 데이터 StratifiedKFold의 수행결과를 비교해보면 각 교차 검증별 정확도와 평균 검증 정확도가 모두 동일

*cross_val_score(): 여러 개의 평가 지표 반환 가능
학습 데이터에 대한 성능 평가 지표와 수행 시간도 같이 제공

In [ ]:
from sklearn.model_selection import cross_val_score, cross_validate


data=iris_data.data
label=iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


### GridSearchCV:교차검증과 최적 하이퍼 파라미터 튜닝 한 번에

* 하이퍼 파라미터: 머신러닝 알고리즘 구성 주요 요소-> 값을 조정해 알고리즘의 예측 성능 개선할 수 있다

* GridSearchCV:교차 검증을 기반으로 이 하이퍼 파라미터의 최적 값 찾게 해줌

* 데이터 세트를 cross-validation을 위한 학습/테스트 세트로 자동으로 분할한 뒤에 하이퍼 파라미터 그리드에 기술된 모든 파라미터를 순차적으로 적용해 최적의 파라미터를 찾을 수 있게함

* 최적의 파라미터를 순차적으로 편리하게 찾게 해주지만, 시간이 오래걸림
  * estimator:classifier, pipeline이 사용될 수 있다
  * param_grid:key+리스트 값을 가지는 딕셔너리가 주어진다. estimator의 튜닝을 위해 파라미터명과 사용될 여러 파라미터값을 지정한다.
  * scoring: 예측 성능을 측정할 평가방법 지정. 보통은 사이킷런의 성능 평가 지표를 지정하는 문자열(ex)정확도-accuracy)로 지정하나 별도의 성능 평가 지표 함수도 지정할 수 있다
  * cv: 교차검증을 위해 분할되는 학습/테스트의 개수를 지정
  * refit: 디폴트가 True 이며 True로 생성 시 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습시킴

In [ ]:
#결정 트리 알고리즘의 여러 하이퍼 파라미터를 순차적으로 변경하면서 최고 성능을 가지는 파라미터 조합 찾기
#파라미터의 집합 만들고 순차적으로 적용해 최적화 수행

grid_parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [ ]:
from sklearn.model_selection import GridSearchCV


#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리

iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)

dtree=DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정

parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}


In [ ]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train,test set fold로 나누어 테스트 수행 설정
#refit=True가 default. True면 가장 좋은 파라미터 설정으로 재학습
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습,평가
grid_dtree.fit(X_train,y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

=>max_depth와 min_samples_split을 순차적으로 총 6번 변경해 학습 및 평가 수행
* params칼럼에는 수행할 때마다 적용된 하이퍼 파라미터값
* rank_test_score: 하이퍼 파라미별로 성능이 좋은 score 순위. 1이 가장 뛰어난 순위 이때의 파라미터가 최적의 하이퍼 파라미터
* mean_test_score: 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값
* best_params_: 최고 성능 하이퍼 파라미터 값 결과

* best_score_ : 최고 성능 하이퍼 파라미터 평가 결과값

In [ ]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [ ]:
#GridSsearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_은 이미 최적 학습이 됐으므로 별도 학습이 필요없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도:0.9667


일반적으로 학습 데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤에 별도의 테스트 세트에서 이를 평가하는 것이 일반적인 머신러닝 모델 적용 방법

####데이터 전처리
:ML 알고리즘은 데이터에 기반하고 있기 때문에 어떤 데이터를 입력으로 가지느냐에 따라 결과도 크게 달라질 수 있다

* 결손값(NaN,NULL) 허용되지 않음-> 고정된 다른 값으로 변환해야함
  * NULL 값 얼마 되지 않으면 피처의 평균값으로 간단히 대체 가능
  * NULL 값 대부분이면 해당 피처 드롭하는 게 좋음
* 사이킷런 머신러닝 알고리즘은 문자열 값을 입력값으로 허용되지 않음->숫자형 변환 필요
  * 문자형: 카테고리형 피처, 텍스트형 피처
    * 텍스트형: 피처 벡터화, 불필요하단 판단 시 삭제 

### 데이터 인코딩

#### 레이블 인코딩(label-encoding)
:카테고리 피처를 코드형 숫자로 변환

 <font color='blue'> 01,02도 문자형이므로 1,2 와 같은 숫자형으로 구분해야함


 =>사이킷런: LabelEndcoder로 객체 생성 후 fit() transform()을 호출 해 레이블 인코딩 수행

* 일괄적인 숫자값으로 변환되다 보니 몇몇 ML 알고리즘에서 이를 적용 시 예측 성능이 떨어짐-> 숫자 값의 경우 크고 작음에 대한 특성 발생하기 때문
but, 큰 값 아니고 단순 특성, 중요도나 가중치 부여x

=>판다스:get_dummies()

In [ ]:
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder을 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)


인코딩 변환값: [0 1 4 5 3 3 2 2]


In [ ]:
#데이터 많을 때 직관적으로 인코딩확인
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
#인코딩된 값 다시 디코딩
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


####원-핫 인코딩(One-Hot encoding)
:피처 값의 유형에 따라 새로운 피처를 추가해 고유값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식

* 행 형태로 돼 있는 피처의 고유값을 열 형태로 차원을 변환한 뒤, 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0 표시

=>사이킷런에서 OneHotEncoder 클래스로 쉽게 변환 가능
* 주의점
 * OneHotEncoder로 변환하기 전 모든 문자열 값이 숫자형 값으로 변환되어야 함
 * 입력 값으로 2차원 데이터가 필요
 

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

#2차원 데이터로 변환
labels=labels.reshape(-1,1)

#원-핫 인코딩 적용
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [ ]:
#판다스 이용
import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_컴퓨터
0        1         0        0         0         0
1        0         1        0         0         0
2        0         0        0         0         1
3        0         0        0         1         0
4        0         0        0         1         0
5        0         0        1         0         0
6        0         0        1         0         0

###피처 스케일링과 정규화
* 피처 스케일링: 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
 * 표준화: 데이터의 피처 각각이 평균이 0, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환
 xi_new=(xi-mean(x))/stdev(x)
 * 정규화: 서로 다른 처의 크기를 통일하기 위해 크기를 변환해주는 개념.0~1의 값으로 변홤
  * 개별 데이터의 크기를 모두 똑같은 단위로 변경
xi_new=(xi-min(x))/(max(x)-min(x))

* 사이킷런의 Normalizer 모듈과의 차이: 사이킷런 Normalizer 모듈은 선형대수에서 정규화 개념이 적용됐으며, 개별 벡터의 크기를 맞추기 위해 변환하는 것을 의미

=>개별 벡터를 모든 피처벡터의 크기로 나눠줌
xi_new=xi/sqrt(xi^2+yi^2+zi^2)


* 사이킷런의 StandardSclaer
:개별 피처를 평균이 0이고 분산이 1인 값으로 변환

사이킷런에서 구현한 RBF 커널을 이용하는 서포트 벡터머신이나 선형 회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현됐기 때문에 사전에 표준화를 적용하는 것은 예측 성능 향상에 중요 요소

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

#붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)


print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler

#StandardScaler의 객체 생성
scaler=StandardScaler()
#StandardScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 DataFrame으로 반환
iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())


feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


->모든 칼럼 값의 평균이 0에 아주 가까운 값으로, 분산은 1에 아주 가까운 값으로 변환됨


* MinMaxScaler: 데이터값으로 0과 1사이의 범위 값으로 변환(음수 있으면 -1과 1사이로 변환)
 * 데이터의 분포가 가우시안 분포가 아닐 경우에 Min,Max Scaler을 적용해 볼 수 있다

In [ ]:
from sklearn.preprocessing import MinMaxScaler
#MinMaxScaler 객체 생성
scaler=MinMaxScaler()
#MinMaxScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


* 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점
:StandardScaler이나 MixMaxScaler와 같은 Scaler 객체를 이용해 데이터의 스케일링 변환 시, 
  * fit()은 데이터 변환을 위한 기준 정보 설정을 적용(최솟값,최댓값)
  * transform()은 fit에서 설정된 정보를 이용해 데이터를 변환
  * fit_transform()은 fit()과 transform() 한번에 적용

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
#scaler 클래스의 fit() transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경
train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)


In [ ]:
#train_data.MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0-1 값으로 변환
scaler=MinMaxScaler()

#fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

#1/10 scale로 train_array 데이터 변환함. 원본 10->1로 변환됨
train_scaled=scaler.transform(train_array)

print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
#test_data.MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정
scaler.fit(test_array)

#1/5 scale로 test_array 데이터 변환. 원본 5->1로 변환
test_scaled=scaler.transform(test_array)

#test_array의 scale 변환 출력
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))



원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


->서로 다른 원본값이 동일한 값으로 변환되는 결과를 초래

머신러닝 모델은 학습데이터를 기반으로 학습되기 때문에 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 하며, 테스트 데이터의 1값은 학습 데이터와 동일하게 0,1 값으로 변환돼야 함

->이미 fit이 적용된 scaler 객체를 이용해 테스트 데이터를 transform()으로 변환





In [ ]:
from scipy.spatial import transform
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

#test_array에 scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함
test_scaled=scaler.transform(test_array)
print('\n원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]



* 가능하다면 전체 데이터의 스케일링 변환을 적용한뒤 학습과 테스트 데이터로 분리
* 안된다면 테스트 데이터 변환 시에는 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 scaler 객체를 이용해  transform() 으로 변환//
여기까지 과제 범위

